## TENSORS
##### Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

##### Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!

In [2]:
import torch
import numpy as np

## Initialiazing a Tensor

##### Method 1: Directly from Data

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


##### Method 2: from a numpy array

In [4]:
np_array = np.array(data)
np_data = torch.from_numpy(np_array)
print(np_data)

tensor([[1, 2],
        [3, 4]])


#### Method 3: From another tensor
##### This method retains the properties like shape and datatype of the passed tensor unless "over-ridden"

In [6]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")
rand_ones = torch.rand_like(x_data, dtype= torch.float)
print(f"Random Tensor: \n {rand_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.2012, 0.6462],
        [0.8755, 0.4420]]) 



#### With random or constant values:

In [9]:
shape = (2,3)
zero_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
rand_tensor = torch.rand(shape)

print(f"Zeros Tensor: \n {zero_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Random Tensor: \n {rand_tensor} \n")

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Random Tensor: 
 tensor([[0.7253, 0.0263, 0.8162],
        [0.1952, 0.3615, 0.8597]]) 



## Attributes of a Tensor

In [12]:
tensor = torch.rand(3,4)
print(f"The tensor is: \n {tensor} \n")

print(f"Shape of tensor is: {tensor.shape}")
print(f"Data type of tensor is: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

The tensor is: 
 tensor([[0.4671, 0.1429, 0.7500, 0.9070],
        [0.8266, 0.9489, 0.2190, 0.4144],
        [0.0149, 0.5282, 0.3692, 0.2246]]) 

Shape of tensor is: torch.Size([3, 4])
Data type of tensor is: torch.float32
Device tensor is stored on: cpu


## Operations on Tensors


In [31]:
tensor = torch.ones(4,4)
print(f"Tensor is : {tensor} \n")

Tensor is : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 



In [32]:
print('first row:',tensor[0])
print('First Column:',tensor[:,0])
print('Last row:', tensor[-1])
print('Last Column:', tensor[:,-1])
tensor[:,2] = 0 #replace third column with all zeros
print(f"New tensor is: \n {tensor}")

first row: tensor([1., 1., 1., 1.])
First Column: tensor([1., 1., 1., 1.])
Last row: tensor([1., 1., 1., 1.])
Last Column: tensor([1., 1., 1., 1.])
New tensor is: 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


#### Joining tensors You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining op that is subtly different from torch.cat.

In [34]:
joined_tensor = torch.cat([tensor,tensor,tensor], dim = 0)
print(joined_tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])


##### Arithmetic operations

In [35]:
z1 = tensor @ tensor.T
z2 = tensor.matmul(tensor.T)
z3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out = z3)

y1 = tensor * tensor.T
y2 = tensor.mul(tensor.T)
y3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out = y3)

print(f"z1: \n {z1} \n")
print(f"z2: \n {z2} \n")
print(f"z3: \n {z3} \n")
print(f"y1: \n {y1} \n")
print(f"y2: \n {y2} \n")
print(f"y3: \n {y3} \n")


z1: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

z2: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

z3: 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

y1: 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [0., 0., 0., 0.],
        [1., 1., 0., 1.]]) 

y2: 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [0., 0., 0., 0.],
        [1., 1., 0., 1.]]) 

y3: 
 tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [0., 0., 0., 0.],
        [1., 1., 0., 1.]]) 



#### Single-element tensors If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [36]:
agg = tensor.sum()
agg1 = agg.item()
print(f"Data Type of {agg} is: {type(agg1)} ")

Data Type of 12.0 is: <class 'float'> 


#### In-place operations Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.

In [37]:
print(tensor, "\n")
tensor.add_(4)
print(tensor)

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]]) 

tensor([[5., 5., 4., 5.],
        [5., 5., 4., 5.],
        [5., 5., 4., 5.],
        [5., 5., 4., 5.]])
